<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="MimeKit" Version="4.15.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
    <PackageReference Include="PuppeteerSharp" Version="20.1.2" />
    <PackageReference Include="QuestPDF" Version="2024.12.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainLayer\DomainLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
